version: '2'

services:

 mail:
  build: mail
  domainname: example.com
  hostname: mail
  networks:
   - stdnet
  volumes_from:
   - maildata
  ports:
   - "443:443"
   - "25:25"
   - "587:587"
   - "143:143"
   - "993:993"
   - "110:110"
   - "995:995"
   - "4190:4190"

 maildata:
  build: mail-data

 nginx:
  build: nginx
  domainname: example.com
  hostname: nginx
  networks:
   - stdnet
  volumes_from:
   - nginxdata
  ports:
   - "80:80"
   - "443:443"
  restart: always

 nginxdata:
  build: nginx-data

 owncloud:
  build: owncloud
  domainname: example.com
  hostname: owncloud
  restart: always
  networks:
   - stdnet
#  volumes:
#   - /srv/owncloud/config:/var/www/html/config
#   - /srv/owncloud/data:/var/www/html/data
  volumes_from:
   - ownclouddata

 ownclouddata:
  build: owncloud-data

 ldapaccountmanager:
  build: ldap-account-manager
  domainname: example.com
  hostname: ldapaccountmanager
  networks:
   - stdnet
  restart: always
# ports:
#  - "80:80"

 openldap:
  image: osixia/openldap
  domainname: example.com
  hostname: openldap
  networks:
   - stdnet
  volumes_from:
   - openldapdata
  restart: always
  ports:
 #  - '389:389'
   - '636:636'
  environment:
   LDAP_DOMAIN: "example.com"
   LDAP_BASE_DN: "dc=example,dc=com"
   LDAP_ADMIN_PASSWORD: "Password1!"
   LDAP_CONFIG_PASSWORD: "Password1!"

 openldapdata:
  build: openldap-data

 mysql:
  image: 'mysql:latest'
  restart: always
  domainname: example.com
  hostname: mysql
  networks:
   - stdnet
  environment:
   - MYSQL_ROOT_PASSWORD='my-secret-pw'
   - MYSQL_USER='example-user'
   - MYSQL_PASSWORD='my-secret-pw'
   - MYSQL_DATABASE='example-database'
#  ports:
#   - '3306:3306'
#  volumes:
#   - /srv/mysql:/var/lib/mysql
  volumes_from:
   - mysqldata
 
 mysqldata:
  build: mysql-data
 
 postgresql:
  image: 'postgres:latest'
  restart: always
  domainname: example.com
  hostname: postgresql
  networks:
   - stdnet
  environment:
   - POSTGRES_PASSWORD='my-secret-pw'
   - POSTGRES_USER='example-user'
   - POSTGRES_DB='example-database'
  ports:
   - '5432:5432'
  volumes_from:
   - postgresqldata
 
 postgresqldata:
  build: postgresql-data

networks:
 stdnet:
