FROM jenkins
USER root
RUN apt-get update && apt-get install -y git cmake build-essential libboost-all-dev libpoco-dev qt5-default qttools5-dev-tools qttools5-dev libqt5webkit5-dev doxygen texlive
USER jenkins
